#  ███████╗██████╗ ██╗███████╗███╗  ██╗██████╗  ██████╗███████╗██╗  ██╗████████╗███████╗███╗  ██╗██████╗ ███████╗██████╗
#  ██╔════╝██╔══██╗██║██╔════╝████╗ ██║██╔══██╗██╔════╝██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝████╗ ██║██╔══██╗██╔════╝██╔══██╗
#  █████╗  ██████╔╝██║█████╗  ██╔██╗██║██║  ██║╚█████╗ █████╗   ╚███╔╝    ██║   █████╗  ██╔██╗██║██║  ██║█████╗  ██║  ██║
#  ██╔══╝  ██╔══██╗██║██╔══╝  ██║╚████║██║  ██║ ╚═══██╗██╔══╝   ██╔██╗    ██║   ██╔══╝  ██║╚████║██║  ██║██╔══╝  ██║  ██║
#  ██║     ██║  ██║██║███████╗██║ ╚███║██████╔╝██████╔╝███████╗██╔╝╚██╗   ██║   ███████╗██║ ╚███║██████╔╝███████╗██████╔╝
#  ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚══╝╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚══╝╚═════╝ ╚══════╝╚═════╝

mysql:
  username: ""
  password: ""
  database: ""
  host: ""
  port: 3306

system-messages:
  no-perm: "&cYou do not have permission to use this command!"